container:
    image: l.gcr.io/google/bazel:latest
task:
    name: Build the example document
    build_script: bazel build //example:my_report
task:
    name: Build all package tests
    build_script: bazel build //packages:all
