name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        folder:
          - "example"
          - "packages"
        platform:
          - ubuntu-latest
          - macos-latest


    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3
      - name: Mount bazel caches
        uses: actions/cache@v3
        with:
          path: |
            "~/.cache/bazel"
            "~/.cache/bazel-repo"
          key: bazel-cache-${{ hashFiles('**/BUILD.bazel', '**/*.bzl', 'WORKSPACE') }}
          restore-keys: bazel-cache-
      - name: Build ${{ matrix.folder }}
        env:
          XDG_CACHE_HOME: ~/.cache/bazel-repo
        run: bazel build //${{ matrix.folder }}:all
